import { describe, expect, it } from "vitest";
import {
  canEditStructuredTriggerDraft,
  combineDataTypeForDatabase,
  createColumnDrafts,
  createTriggerDrafts,
  dataTypeLengthInputValue,
  DATA_TYPE_OPTIONS,
  defaultNewColumnDataType,
  getDefaultLengthForType,
  hasExistingColumnTypeChange,
  isDataTypeLengthDisabled,
  parseExtraToColumnExtra,
  rehydrateColumnDraftsFromMetadata,
  resolveInsertColumnIndex,
  splitDataType,
  generateIndexName,
  generateUniqueIndexName,
  filterStructureIndexColumnOptions,
} from "@/lib/table/tableStructureEditorState";

describe("tableStructureEditorState", () => {
  it("allows structured trigger draft editing for openGauss", () => {
    const [existing] = createTriggerDrafts([{ name: "ORDERS_AUDIT", timing: "AFTER", event: "INSERT OR UPDATE", statement: "BEGIN NULL; END;" }]);
    if (!existing) throw new Error("expected an existing trigger draft");

    expect(canEditStructuredTriggerDraft("opengauss", existing)).toBe(true);
    expect(canEditStructuredTriggerDraft(undefined, existing)).toBe(false);
  });

  it("hydrates openGauss/Postgres type parameters returned separately from the data type", () => {
    const columns = createColumnDrafts(
      [
        {
          name: "display_name",
          data_type: "varchar",
          is_nullable: true,
          column_default: null,
          is_primary_key: false,
          extra: null,
          character_maximum_length: 255,
        },
        {
          name: "amount",
          data_type: "numeric",
          is_nullable: false,
          column_default: null,
          is_primary_key: false,
          extra: null,
          numeric_precision: 12,
          numeric_scale: 2,
        },
        {
          name: "attempts",
          data_type: "integer",
          is_nullable: false,
          column_default: null,
          is_primary_key: false,
          extra: null,
          numeric_precision: 32,
          numeric_scale: 0,
        },
        {
          name: "code",
          data_type: "character varying(64)",
          is_nullable: true,
          column_default: null,
          is_primary_key: false,
          extra: null,
          character_maximum_length: 64,
        },
      ],
      "opengauss",
    );

    expect(columns.map((column) => column.dataType)).toEqual(["varchar(255)", "numeric(12,2)", "integer", "character varying(64)"]);
    expect(columns.map((column) => column.original?.data_type)).toEqual(["varchar(255)", "numeric(12,2)", "integer", "character varying(64)"]);
    expect(dataTypeLengthInputValue("opengauss", columns[0]?.dataType ?? "")).toBe("255");
  });

  it("parses PostgreSQL / openGauss identity metadata", () => {
    expect(parseExtraToColumnExtra("generated always as identity", "opengauss")).toEqual({
      identity: { generation: "ALWAYS" },
    });
    expect(parseExtraToColumnExtra("generated by default as identity (start with 1 increment by 2)", "postgres")).toEqual({
      identity: { generation: "BY DEFAULT", seed: 1, increment: 2 },
    });
  });

  it("splits and combines data types with parameters", () => {
    expect(splitDataType("varchar(255)")).toEqual({ baseType: "varchar", params: "255" });
    expect(splitDataType("numeric(10,2)")).toEqual({ baseType: "numeric", params: "10,2" });
    expect(combineDataTypeForDatabase("opengauss", "varchar", "100")).toBe("varchar(100)");
  });

  it("disables length field for fixed-size Postgres types", () => {
    expect(isDataTypeLengthDisabled("postgres", "integer")).toBe(true);
    expect(isDataTypeLengthDisabled("postgres", "bigint")).toBe(true);
    expect(isDataTypeLengthDisabled("postgres", "boolean")).toBe(true);
    expect(isDataTypeLengthDisabled("opengauss", "varchar")).toBe(false);
  });

  it("generates default new column data type", () => {
    expect(defaultNewColumnDataType("opengauss")).toBe("varchar(255)");
    expect(defaultNewColumnDataType("postgres")).toBe("varchar(255)");
  });

  it("resolves insertion column index correctly", () => {
    const columns = [{ id: "col1" }, { id: "col2" }, { id: "col3" }];
    expect(resolveInsertColumnIndex(columns, "col2")).toBe(2);
    expect(resolveInsertColumnIndex(columns, null)).toBe(3);
    expect(resolveInsertColumnIndex(columns, "unknown")).toBe(3);
  });

  it("generates auto index names and unique names", () => {
    expect(generateIndexName("users", ["email"])).toBe("USERS_EMAIL_IDX");
    expect(generateUniqueIndexName("users", ["email"], ["USERS_EMAIL_IDX"])).toBe("USERS_EMAIL_IDX_2");
  });

  it("filters structure index column options", () => {
    const available = ["id", "name", "email", "created_at"];
    const selected = ["id", "removed_col"];
    const filtered = filterStructureIndexColumnOptions(available, selected, "em");
    expect(filtered).toContain("email");
  });

  it("detects existing column type changes", () => {
    const originalColumn = {
      name: "age",
      data_type: "integer",
      is_nullable: true,
      column_default: null,
      is_primary_key: false,
      extra: null,
    };
    const columns = [
      {
        id: "existing:age",
        name: "age",
        dataType: "bigint",
        isNullable: true,
        defaultValue: "",
        comment: "",
        isPrimaryKey: false,
        characterSet: "",
        collation: "",
        extra: {},
        original: originalColumn,
        markedForDrop: false,
      },
    ];
    expect(hasExistingColumnTypeChange(columns)).toBe(true);
  });
});
